# Generated by Django 6.0.2 on 2026-03-03 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255)),
                ('course_number', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=50)),
                ('class_section', models.CharField(blank=True, max_length=50, null=True)),
                ('instructor_name', models.CharField(max_length=255)),
                ('lecture_number', models.IntegerField(blank=True, null=True)),
                ('date_of_lecture', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('notes_file', models.FileField(upload_to='notes/')),
                ('rating', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
